# .github/workflows/build.yml

name: Build SnowFox

on:
  push:
    branches:
      - main
      - 'release/*'

env:
  VERSION: '1.0.0'  # Defina aqui a versão que você deseja usar

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make cmake

      - name: Check if build directory exists (Linux)
        run: |
          if [ ! -d "build" ]; then
            mkdir build
          fi

      - name: Build snowfox for Linux
        run: |
          cd build
          cmake ../src -DCMAKE_CXX_STANDARD=20
          make snowfox
          mv snowfox snowfox-linux-${VERSION}

      - name: Commit and push build artifacts
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add build/snowfox-linux-${VERSION}
          git commit -m "Add build artifacts for Linux version ${VERSION}"
          git push origin main

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Install CMake
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

      - name: Check if build directory exists (Windows)
        run: |
          if not exist build (
            mkdir build
          )

      - name: Build snowfox for Windows
        run: |
          cd build
          cmake ../src -G "Visual Studio 16 2019" -A x64 -DCMAKE_CXX_STANDARD=20
          cmake --build . --config Release --target snowfox
          move Release\snowfox.exe snowfox-win-${VERSION}.exe

      - name: Commit and push build artifacts
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add build/snowfox-win-${VERSION}.exe
          git commit -m "Add build artifacts for Windows version ${VERSION}"
          git push origin main
