# .github/workflows/build.yml

name: Build src/snowfox.cpp

on:
  push:
    branches:
      - main
      - 'release/*'

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y g++ make cmake

      - name: Build src/snowfox.cpp
        run: |
          mkdir -p build
          cd build
          cmake ../src -DCMAKE_CXX_STANDARD=20
          make

      - name: Save build artifacts to repository
        run: |
          mkdir -p build_artifacts
          cp -r build/* build_artifacts/
          mv build_artifacts build

      - name: Commit and push build artifacts
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add build
          git commit -m "Add build artifacts"
          git push origin main

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Install CMake
        run: |
          # Install CMake on Windows
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

      - name: Build src/snowfox.cpp
        run: |
          mkdir build
          cd build
          cmake ../src -G "Visual Studio 16 2019" -A x64 -DCMAKE_CXX_STANDARD=20
          cmake --build . --config Release

      - name: Save build artifacts to repository
        run: |
          mkdir build_artifacts
          cp -r build/Release/* build_artifacts/
          mv build_artifacts build/Release

      - name: Commit and push build artifacts
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add build/Release
          git commit -m "Add build artifacts"
          git push origin main
