name: Build SnowFox

on:
  push:
    branches:
      - main
      - experimental-betterbuild

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build SnowFox versions
        id: build
        run: |
          source build.sh
          cat release_info.txt >> $GITHUB_ENV

      - name: Create GitHub Release with binary attachments
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        with:
          tag_name: v${{ steps.build.outputs.version }}
          release_name: Release v$VERSION
          body: |
            ${{ steps.build.outputs.description }}

      - name: Upload snowfox binary to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/snowfox-linux-$VERSION
          asset_name: snowfox-linux-$VERSION
          asset_content_type: application/octet-stream
