# .github/workflows/build.yml

name: Build SnowFox

on:
  push:
    branches:
      - main
      - 'release/*'

env:
  VERSION: '1.0.0'  # Defina aqui a versão que você deseja usar

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clean previous build artifacts (Linux)
        run: |
          rm -rf build
          mkdir build

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make cmake

      - name: Build snowfox for Linux
        run: |
          cd build
          cmake ../src -DCMAKE_CXX_STANDARD=20
          make snowfox
          mv snowfox snowfox-linux-${VERSION}

      - name: Commit and push build artifacts (Linux)
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add build/snowfox-linux-${VERSION}
          git commit -m "Add build artifacts for Linux version ${VERSION}"
          git push origin main