# .github/workflows/build.yml

name: Build src/snowfox.cpp

on:
  push:
    branches:
      - main
      - 'release/*'

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y g++ make cmake

      - name: Build src/snowfox.cpp
        run: |
          mkdir -p build
          cd build
          cmake ../src
          make

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts-linux
          path: build/Release/snowfox-linux

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Install CMake
        uses: chrislennon/action-cmake@v1

      - name: Build src/snowfox.cpp
        run: |
          mkdir build
          cd build
          cmake ../src -G "Visual Studio 16 2019" -A x64
          cmake --build . --config Release

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts-windows
          path: build/Release/snowfox-win.exe
