name: Build SnowFox

on:
  push:
    branches:
      - main

env:
  VERSION: '0.0.1'

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clean previous build artifacts (Linux)
        run: |
          rm -rf build
          mkdir build

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make cmake

      - name: Build snowfox for Linux
        run: |
          cd build
          cmake ../src -DCMAKE_CXX_STANDARD=20
          make snowfox
          mv snowfox snowfox-linux-${VERSION}

      - name: Create GitHub Release with binary attachment
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release v${{ env.VERSION }}
          body: |
            Release v${{ env.VERSION }}
            - Built for Linux

      - name: Upload snowfox binary to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/snowfox-linux-${{ env.VERSION }}
          asset_name: snowfox-linux-${{ env.VERSION }}
          asset_content_type: application/octet-stream
