name: Build SnowFox

on:
  push:
    branches:
      - main

env:
  VERSION_FILE: version.txt
  DESCRIPTION_FILE: description.txt

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clean previous build artifacts (Linux)
        run: |
          rm -rf build
          mkdir build

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make cmake

      - name: Read version from file
        id: read_version
        run: echo "::set-output name=version::$(cat $VERSION_FILE)"

      - name: Read description from file
        id: read_description
        run: echo "::set-output name=description::$(cat $DESCRIPTION_FILE)"

      - name: Build snowfox for Linux
        run: |
          cd build
          cmake ../src -DCMAKE_CXX_STANDARD=20
          make snowfox
          mv snowfox snowfox-linux-${{ env.VERSION }}

      - name: Create GitHub Release with binary attachment
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        with:
          tag_name: v${{ steps.read_version.outputs.version }}
          release_name: Release v${{ steps.read_version.outputs.version }}
          body: |
            ${{ steps.read_description.outputs.description }}

      - name: Upload snowfox binary to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/snowfox-linux-${{ steps.read_version.outputs.version }}
          asset_name: snowfox-linux-${{ steps.read_version.outputs.version }}
          asset_content_type: application/octet-stream
